backend:
  name: git-gateway
  branch: master

media_folder: src/images
public_folder: images

site_url: https://www.calciomontesacro.com

collections:
  - name: "blog_en"
    label: "Blog in English"
    description: "Blog post content and information - English"
    folder: "content/blog"
    filter: { field: "language", value: "en" }
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "post" }
      - { name: "language", label: "Language", widget: "hidden", default: "en" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Content", widget: "markdown" }
  - name: "blog_it"
    label: "Il Blog in Italiano"
    description: "Contenuto e informazione dei post del blog - Italiano"
    folder: "content/blog"
    filter: { field: "language", value: "it" }
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "post" }
      - { name: "language", label: "Lingua", widget: "hidden", default: "it" }
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "title", label: "Titolo", widget: "string" }
      - { name: "body", label: "Contenuto", widget: "markdown" }
  - name: "news_en"
    label: "News in English"
    description: "News post content and information - English"
    folder: "content/news"
    filter: { field: "language", value: "en" }
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "post" }
      - { name: "language", label: "Language", widget: "hidden", default: "en" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Content", widget: "markdown" }
  - name: "news_it"
    label: "Le Notizie in Italiano"
    description: "Contenuto e informazione dei posti delle notizie - Italiano"
    folder: "content/news"
    filter: { field: "language", value: "it" }
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "post" }
      - { name: "language", label: "Lingua", widget: "hidden", default: "it" }
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "title", label: "Titolo", widget: "string" }
      - { name: "body", label: "Contenuto", widget: "markdown" }
  - name: "schedule_en"
    label: "Schedule in English"
    description: "Schedule and results - English"
    folder: "content/schedule"
    filter: { field: "language", value: "en" }
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "schedule" }
      - { name: "language", label: "Language", widget: "hidden", default: "en" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "type", label: "Type", widget: "select", options: ["Practice", "Match"]}
      - { name: "title", label: "Title", widget: "string" }
      - { name: "venue", label: "Venue", widget: "string", default: "Parco Sannazzaro" }
      - { name: "opposing_team", label: "Opposing Team", widget: "string", required: false }
      - { name: "home", label: "Home", widget: "boolean", required: false }
      - { name: "score_ms", label: "Score (MS)", required: false, widget: "number", valueType: "int" }
      - { name: "score_other", label: "Score (Other)", required: false, widget: "number", valueType: "int" }
  - name: "schedule_it"
    label: "Calendario in Italiano"
    description: "Calendario e risultato - Italiano"
    folder: "content/schedule"
    filter: { field: "language", value: "it" }
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "schedule" }
      - { name: "language", label: "Lingua", widget: "hidden", default: "it" }
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "type", label: "Tipo", widget: "select", options: ["Allenamento", "Partita"]}
      - { name: "title", label: "Titolo", widget: "string" }
      - { name: "venue", label: "Sede", widget: "string", default: "Parco Sannazzaro" }
      - { name: "opposing_team", label: "Squadra Avversaria", widget: "string", required: false }
      - { name: "home", label: "Di Casa", widget: "boolean", required: false }
      - { name: "score_ms", label: "Punteggio (MS)", widget: "number", valueType: "int", required: false }
      - { name: "score_other", label: "Punteggio (Altre)", widget: "number", valueType: "int", required: false }